export const SET_USER_COLORS = "SET_USER_COLORS";
export const SET_USER_RESTRICTIONS = "SET_USER_RESTRICTIONS";
export const SET_BAR_COLORS = "SET_BAR_COLORS";
export const SET_LIVE_PAGE_CONFIG = "SET_LIVE_PAGE_CONFIG";
export const GET_ANALYSIS_DATA = "GET_ANALYSIS_DATA";
